function [BLKGenerator, MG] = BG_iCheb_BAM_PMFCmj_FI1(node_precision, use_spmd)
%UNTITLED Summary of this function goes here
%   Detailed explanation goes here

if(nargin < 1)
    node_precision = 'double';
end
if(nargin < 2)
    use_spmd = true;
end

node_ordering  = 'rclassical';

% -- select method --------------------------------------------------------------------------------
MG = PBMGenerator(struct( ...
    'NodeSet_generator', IChebNSG(node_ordering, node_precision), ...
    'ODEPoly_generator', Adams_PG('PMFO', 'PMFOmj', FixedInputEPG(struct('l', 1)), 'diagonally_implicit') ...
    ));

% -- select extrapolation -------------------------------------------------------------------------
EG = PBMGenerator(struct( ...
    'NodeSet_generator', IChebNSG(node_ordering, node_precision), ...
    'ODEPoly_generator', YExtrap_PG('PMFO') ...
    ));

if(use_spmd)
    solver_class = @MutableDIPBLK;
else
    solver_class = @MutableDIBLK;
end


BLKGenerator = BLKSolverGenerator( ...
    struct(...
    'solver_class',              solver_class, ...
    'method_generator',          MG, ...
    'extrapolator_generator',    EG, ...
    'output_coefficient_handle', @Output_IChebAdams_PMFC, ...
    'name',                      'iCheb-BAM-PMFCmj-FI1-' ...
    ) ...
);

end